#!/usr/bin/with-contenv bash

# create default xsettings
if [ ! -f "${HOME}/.xsettingsd" ]; then
  echo "Xft/DPI 98304" > "${HOME}/.xsettingsd"
fi
chown abc:abc "${HOME}/.xsettingsd"

# run
exec s6-setuidgid abc \
  xsettingsd
