#!/usr/bin/with-contenv bash

# Run Xvfb server with required extensions
exec s6-setuidgid abc \
  /usr/bin/Xvfb \
    "${DISPLAY}" \
    -screen 0 "8192x4096x${DISPLAY_CDEPTH}" \
    -dpi "${DISPLAY_DPI}" \
    +extension "COMPOSITE" \
    +extension "DAMAGE" \
    +extension "GLX" \
    +extension "RANDR" \
    +extension "RENDER" \
    +extension "MIT-SHM" \
    +extension "XFIXES" \
    +extension "XTEST" \
    +iglx \
    +render \
    -nolisten "tcp" \
    -ac \
    -noreset \
    -shmem
