#!/usr/bin/with-contenv bash

# Folder setup
mkdir -p /run/dbus
chown abc:abc /run/dbus
rm -f /run/dbus/pid
chown dbus:dbus /run/dbus

# Run dbus
exec s6-setuidgid \
  dbus \
  dbus-daemon \
    --system \
    --nofork \
    --nosyslog > /dev/null 2>&1
