#!/usr/bin/with-contenv bash


# Make sure this is a priv container
if [ -e /dev/cpu_dma_latency ]; then
  if [ "${START_DOCKER,,}" == "true" ]; then
    mount -t tmpfs none /tmp
    if ! command -v dockerd >/dev/null 2>&1; then
      echo "[ls.io-init] docker not installed on this variant (DinD deferred) - service idle"
      sleep infinity
    fi
    exec /usr/local/bin/dockerd-entrypoint.sh -l error
  else
    sleep infinity
  fi
fi
# if anything goes wrong with Docker don't loop
sleep infinity
