#!/bin/bash

# Native Steam install for the Fedora selkies baseimage, steam comes from rpmfusion.

LOCKFILE="/var/lib/selkies/steam-installed"
STEAM_PRELOAD="/usr/lib/selkies_joystick_interposer.so:/usr/lib/libudev.so.1.0.0-fake:/usr/lib/selkies_joystick_interposer_32.so:/usr/lib/libudev.so.1.0.0-fake_32"
# proot-bwrap only probes debian multiarch paths for libfakechroot.so, which it
# needs to run steamwebhelper (proot is too slow for it to start in time)
FAKECHROOT_LIBS=(
  "/usr/lib64/fakechroot/libfakechroot.so:/usr/local/lib/x86_64-linux-gnu/fakechroot/libfakechroot.so"
  "/usr/lib/fakechroot/libfakechroot.so:/usr/local/lib/i386-linux-gnu/fakechroot/libfakechroot.so"
)
ACTION="${1:-}"

# Keep the terminal readable when launched from the dashboard
hold() {
  if [ -t 0 ]; then
    echo
    read -r -p "Press enter to close this window"
  fi
}

fail() {
  echo
  echo "ERROR: $*" >&2
  hold
  exit 1
}

as_root() {
  sudo -n "$@"
}

usage() {
  echo "Usage: $(basename "$0") [install|remove]"
  hold
  exit 1
}

preflight() {
  if [ "$(uname -m)" != "x86_64" ]; then
    fail "Steam is only available for x86_64"
  fi
  if ! sudo -n true >/dev/null 2>&1; then
    fail "passwordless sudo is required and is not available (is HARDEN_DESKTOP or DISABLE_SUDO set?)"
  fi
}

install_steam() {
  if [ -f "${LOCKFILE}" ]; then
    echo "Steam is already installed in this container, launch it from the menu"
    hold
    exit 0
  fi
  echo "**** install steam ****"
  # the shim symlink would collide with the package's /usr/bin/steam
  if grep -qs '#SELKIESSHIM' /usr/bin/steam; then
    as_root rm -f /usr/bin/steam
  fi
  as_root dnf install -y \
    fakechroot-libs \
    fakechroot-libs.i686 \
    libva.i686 \
    mesa-dri-drivers.i686 \
    mesa-va-drivers-freeworld.i686 \
    mesa-vulkan-drivers.i686 \
    steam || fail "could not install the steam package"
  echo "**** expose fakechroot to proot-bwrap ****"
  for pair in "${FAKECHROOT_LIBS[@]}"; do
    as_root mkdir -p "$(dirname "${pair#*:}")"
    as_root ln -sfn "${pair%%:*}" "${pair#*:}"
  done
  echo "**** install 32 bit interposer libs ****"
  as_root cp /opt/lib/libudev.so.1.0.0-fake /opt/lib/libudev.so.1.0.0-fake_32 /usr/lib/
  as_root ldconfig
  echo "**** wrap steam launcher ****"
  # bin_steam.sh names its data dir after $0, so launch it through a link named steam
  as_root ln -sfn bin_steam.sh /usr/lib/steam/steam
  if [ ! -e /usr/bin/steam.distrib ]; then
    as_root mv /usr/bin/steam /usr/bin/steam.distrib
  fi
  as_root tee /usr/bin/steam >/dev/null <<WRAP
#!/bin/bash

# Selkies steam wrapper, generated by /steam.sh

# proton games launch through steam and pick up the interposers from here
monitor_proton_dirs() {
  local SEARCH_DIR="\$HOME/.steam/steam/steamapps/common"
  while kill -0 "\$1" >/dev/null 2>&1; do
    shopt -s nullglob
    for dir in "\$SEARCH_DIR"/*Proton*/; do
      if [ -d "\$dir" ] && [ ! -f "\$dir/user_settings.py" ]; then
        cat > "\$dir/user_settings.py" <<SETTINGS
user_settings = {
    "LD_PRELOAD": "${STEAM_PRELOAD}",
}
SETTINGS
      fi
    done
    shopt -u nullglob
    sleep 1
  done
}

# bubblewrap stand in for containers without user namespaces
export BWRAP="\${BWRAP:-\$HOME/.local/bin/proot-bwrap}"
# 64 and 32 bit joystick interposers and fake udev for gamepads
export LD_PRELOAD="${STEAM_PRELOAD}"

STEAM_ARGS=(-no-cef-sandbox)
if [ -n "\${WAYLAND_DISPLAY}" ]; then
  STEAM_ARGS+=(--ozone-platform=wayland)
fi

/usr/lib/steam/steam "\${STEAM_ARGS[@]}" "\$@" &
STEAM_PID=\$!
monitor_proton_dirs "\${STEAM_PID}" &
wait "\${STEAM_PID}"
WRAP
  as_root chmod 755 /usr/bin/steam
  echo "**** cleanup ****"
  as_root dnf clean all
  as_root mkdir -p "$(dirname "${LOCKFILE}")"
  as_root touch "${LOCKFILE}"
  # Refresh the launcher panel so the new entry shows up
  if [ -f "$HOME/.config/panel-reload" ]; then
    touch "$HOME/.config/panel-reload"
  fi
  echo
  echo "Steam installed, launch it from the menu or with: steam"
  echo "Note: this install lives in the container, re-run it after the container is recreated"
  hold
}

remove_steam() {
  if ! rpm -q steam >/dev/null 2>&1 && [ ! -f "${LOCKFILE}" ]; then
    echo "Steam is not installed in this container"
    hold
    exit 0
  fi
  echo "**** remove launcher wrapper ****"
  if [ -e /usr/bin/steam.distrib ]; then
    as_root rm -f /usr/bin/steam
    as_root mv /usr/bin/steam.distrib /usr/bin/steam
  fi
  as_root rm -f /usr/lib/steam/steam
  for pair in "${FAKECHROOT_LIBS[@]}"; do
    as_root rm -f "${pair#*:}"
  done
  echo "**** remove steam package ****"
  # Deps and the user's steam data are left in place
  as_root dnf remove -y --noautoremove steam || fail "could not remove the steam package"
  as_root dnf clean all
  as_root rm -f "${LOCKFILE}"
  if [ ! -e /usr/bin/steam ] && [ -e /usr/local/bin/steam ]; then
    as_root ln -s /usr/local/bin/steam /usr/bin/steam
  fi
  if [ -f "$HOME/.config/panel-reload" ]; then
    touch "$HOME/.config/panel-reload"
  fi
  echo
  echo "Steam removed, game data in $HOME/.steam and $HOME/.local/share/Steam was left in place"
  hold
}

case "${ACTION}" in
  install)
    preflight
    install_steam
    ;;
  remove|uninstall)
    preflight
    remove_steam
    ;;
  *)
    usage
    ;;
esac
