#!/bin/bash

# Native Steam install for the Ubuntu resolute selkies baseimage.

LOCKFILE="/var/lib/selkies/steam-installed"
STEAM_DEB_URL="https://repo.steampowered.com/steam/archive/stable/steam_latest.deb"
STEAM_PRELOAD="/usr/lib/selkies_joystick_interposer.so:/usr/lib/libudev.so.1.0.0-fake:/usr/lib/selkies_joystick_interposer_32.so:/usr/lib/libudev.so.1.0.0-fake_32"
ACTION="${1:-}"

# Keep the terminal readable when launched from the dashboard
hold() {
  if [ -t 0 ]; then
    echo
    read -r -p "Press enter to close this window"
  fi
}

fail() {
  echo
  echo "ERROR: $*" >&2
  hold
  exit 1
}

as_root() {
  sudo -n env DEBIAN_FRONTEND=noninteractive "$@"
}

usage() {
  echo "Usage: $(basename "$0") [install|remove]"
  hold
  exit 1
}

preflight() {
  if [ "$(uname -m)" != "x86_64" ]; then
    fail "Steam is only available for x86_64"
  fi
  if ! sudo -n true >/dev/null 2>&1; then
    fail "passwordless sudo is required and is not available (is HARDEN_DESKTOP or DISABLE_SUDO set?)"
  fi
}

install_steam() {
  if [ -f "${LOCKFILE}" ]; then
    echo "Steam is already installed in this container, launch it from the menu"
    hold
    exit 0
  fi
  echo "**** enable i386 ****"
  if ! as_root dpkg --print-foreign-architectures | grep -qx i386; then
    as_root dpkg --add-architecture i386 || fail "could not enable the i386 architecture"
  fi
  echo "**** install steam launcher ****"
  curl -o /tmp/steam-launcher.deb -fsSL \
    --retry 5 --retry-all-errors --retry-delay 3 --retry-connrefused --retry-max-time 180 \
    "${STEAM_DEB_URL}" || fail "could not download the steam launcher package"
  as_root apt-get update || fail "apt-get update failed"
  as_root apt-get install -y --no-install-recommends /tmp/steam-launcher.deb || fail "could not install the steam launcher package"
  rm -f /tmp/steam-launcher.deb
  echo "**** install steam deps ****"
  as_root apt-get update || fail "apt-get update failed"
  as_root apt-get install -y --no-install-recommends \
    libasound2-plugins:i386 \
    libc6:i386 \
    libegl1:i386 \
    libfakechroot:amd64 \
    libfakechroot:i386 \
    libfontconfig1:i386 \
    libgbm1:i386 \
    libgl1:i386 \
    libgl1-mesa-dri:i386 \
    libgles2:i386 \
    libglx-mesa0:i386 \
    libva2:i386 \
    libva-drm2:i386 \
    libva-x11-2:i386 \
    libvulkan1:i386 \
    libxkbcommon-x11-0:i386 \
    libxss1:i386 \
    mesa-libgallium:i386 \
    mesa-va-drivers:i386 \
    mesa-vulkan-drivers:i386 \
    steam-libs-amd64 \
    steam-libs-i386 \
    zenity || fail "could not install steam dependencies"
  echo "**** stub steamdeps ****"
  if [ ! -e /usr/bin/steamdeps.distrib ]; then
    as_root dpkg-divert --rename --divert /usr/bin/steamdeps.distrib /usr/bin/steamdeps
  fi
  printf '#!/bin/sh\nexit 0\n' | as_root tee /usr/bin/steamdeps >/dev/null
  as_root chmod 755 /usr/bin/steamdeps
  echo "**** install 32 bit interposer libs ****"
  as_root cp /opt/lib/libudev.so.1.0.0-fake /opt/lib/libudev.so.1.0.0-fake_32 /usr/lib/
  as_root ldconfig
  echo "**** wrap steam launcher ****"
  as_root ln -sfn bin_steam.sh /usr/lib/steam/steam
  if [ ! -e /usr/bin/steam.distrib ]; then
    as_root dpkg-divert --rename --divert /usr/bin/steam.distrib /usr/bin/steam
  fi
  as_root tee /usr/bin/steam >/dev/null <<WRAP
#!/bin/bash

# Selkies steam wrapper, generated by /steam.sh

# proton games launch through steam and pick up the interposers from here
monitor_proton_dirs() {
  local SEARCH_DIR="\$HOME/.steam/steam/steamapps/common"
  while kill -0 "\$1" >/dev/null 2>&1; do
    shopt -s nullglob
    for dir in "\$SEARCH_DIR"/*Proton*/; do
      if [ -d "\$dir" ] && [ ! -f "\$dir/user_settings.py" ]; then
        cat > "\$dir/user_settings.py" <<SETTINGS
user_settings = {
    "LD_PRELOAD": "${STEAM_PRELOAD}",
}
SETTINGS
      fi
    done
    shopt -u nullglob
    sleep 1
  done
}

# bubblewrap stand in for containers without user namespaces
export BWRAP="\${BWRAP:-\$HOME/.local/bin/proot-bwrap}"
# 64 and 32 bit joystick interposers and fake udev for gamepads
export LD_PRELOAD="${STEAM_PRELOAD}"

STEAM_ARGS=(-no-cef-sandbox)
if [ -n "\${WAYLAND_DISPLAY}" ]; then
  STEAM_ARGS+=(--ozone-platform=wayland)
fi

/usr/lib/steam/steam "\${STEAM_ARGS[@]}" "\$@" &
STEAM_PID=\$!
monitor_proton_dirs "\${STEAM_PID}" &
wait "\${STEAM_PID}"
WRAP
  as_root chmod 755 /usr/bin/steam
  echo "**** cleanup ****"
  as_root apt-get clean
  as_root rm -rf /var/lib/apt/lists/*
  as_root mkdir -p "$(dirname "${LOCKFILE}")"
  as_root touch "${LOCKFILE}"
  # Refresh the launcher panel so the new entry shows up
  if [ -f "$HOME/.config/panel-reload" ]; then
    touch "$HOME/.config/panel-reload"
  fi
  echo
  echo "Steam installed, launch it from the menu or with: steam"
  echo "Note: this install lives in the container, re-run it after the container is recreated"
  hold
}

remove_steam() {
  if ! dpkg-query -s steam-launcher >/dev/null 2>&1 && [ ! -f "${LOCKFILE}" ]; then
    echo "Steam is not installed in this container"
    hold
    exit 0
  fi
  echo "**** remove launcher wrapper ****"
  if [ -e /usr/bin/steam.distrib ]; then
    as_root rm -f /usr/bin/steam
    as_root dpkg-divert --rename --remove /usr/bin/steam
  fi
  if [ -e /usr/bin/steamdeps.distrib ]; then
    as_root rm -f /usr/bin/steamdeps
    as_root dpkg-divert --rename --remove /usr/bin/steamdeps
  fi
  as_root rm -f /usr/lib/steam/steam
  echo "**** remove steam launcher ****"
  # Deps, the i386 arch and the user's steam data are left in place
  as_root apt-get purge -y steam-launcher || fail "could not remove the steam launcher package"
  as_root apt-get clean
  as_root rm -rf /var/lib/apt/lists/*
  as_root rm -f "${LOCKFILE}"
  if [ -f "$HOME/.config/panel-reload" ]; then
    touch "$HOME/.config/panel-reload"
  fi
  echo
  echo "Steam removed, game data in $HOME/.steam and $HOME/.local/share/Steam was left in place"
  hold
}

case "${ACTION}" in
  install)
    preflight
    install_steam
    ;;
  remove|uninstall)
    preflight
    remove_steam
    ;;
  *)
    usage
    ;;
esac
